// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Lowest Common Ancestor of a Binary Search Tree
// https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/
// 

/**
 * Definition for a binary tree node.
 * public class TreeNode {
 *     int val;
 *     TreeNode left;
 *     TreeNode right;
 *     TreeNode(int x) { val = x; }
 * }
 */
class Solution {
    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {
        if(root == null)
            return null;
        if(p.val < q.val)
            return helper(root, p, q);
        else
            return helper(root, q, p);  
    }
    public TreeNode helper(TreeNode root, TreeNode p, TreeNode q){
        if(root.val < p.val)
            return lowestCommonAncestor(root.right, p, q);
        if(root.val > q.val)
            return lowestCommonAncestor(root.left, p, q);
        else
            return root;
    }
}

