// 
// Generated by fetch-leetcode-submission project on GitHub.
// https://github.com/gitzhou/fetch-leetcode-submission
// Contact Me: aaron67[AT]aaron67.cc
// 
// Maximize Distance to Closest Person
// https://leetcode.com/problems/maximize-distance-to-closest-person/
// 

class Solution {
    public int maxDistToClosest(int[] seats) {
        //
        int ans = 0;
        
        int i = 0;
        while(seats[i] != 1) i++;
        ans = Math.max(ans, i);
        
        int prev = i;
        i++;
        while(i < seats.length) {
            if(seats[i] == 1) {
                int ind = prev+(i-prev)/2;
                ans = Math.max(ans, ind-prev);
                prev = i;
            }
            i++;
        }
        ans = Math.max(ans, seats.length-1 - prev);
        return ans;
    }
}

