# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Bulls and Cows
# https://leetcode.com/problems/bulls-and-cows/
# 

class Solution(object):
    def getHint(self, secret, guess):
        """
        :type secret: str
        :type guess: str
        :rtype: str
        """

        Count_A = 0
        New_secret ={}
        New_Guess ={}
        Count_B = 0
        for i in range(len(secret)) :

            if secret [i] ==guess[i] :
                Count_A+=1
            else:
                try :
                    New_secret[secret[i]] +=1
                except :
                    New_secret[secret[i]] = 1
                try:
                    New_Guess[guess[i]] +=1
                except :
                    New_Guess[guess[i]] = 1
        for key in  New_secret.keys():
            try:
                Count_B += min(New_secret[key],New_Guess[key])
            except :
                continue 
        return ( str(Count_A)+'A'+str(Count_B)+'B')

