# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Plus One
# https://leetcode.com/problems/plus-one/
# 

class Solution(object):
    def plusOne(self, digits):
        """
        :type digits: List[int]
        :rtype: List[int]
        """
        leng = len(digits)
        for i in range(leng - 1, -1, -1):
            digits[i] += 1
            if digits[i] < 10:
                break
            digits[i] = 0
        
        if digits[0] == 0:
            digits = [1] + digits
        
        return digits


