# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Plus One
# https://leetcode.com/problems/plus-one/
# 

class Solution(object):
    def plusOne(self, digits):
        """
        :type digits: List[int]
        :rtype: List[int]
        """
        if not digits or len(digits) == 0:
            return 
        leng = len(digits)
        i = leng - 1
        while i >= 0 :
            if digits[i] == 9 :
                digits[i] = 0
                i -= 1
            else:
                digits[i] += 1
                return digits
        
        digits.insert(0, 1)
        return digits

