# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Plus One
# https://leetcode.com/problems/plus-one/
# 

class Solution(object):
    def plusOne(self, digits):
        """
        :type digits: List[int]
        :rtype: List[int]
        """
        if not digits or len(digits) == 0:
            return 
        leng = len(digits)
        carry = 0
        if digits[leng - 1] == 9:
            digits[leng - 1] = 0
            carry = 1
        else:
            digits[leng - 1] = digits[leng - 1] + 1

        for i in range(2, leng + 1):
            if digits[leng - i] == 9 and carry == 1:
                digits[leng - i] = 0
                carry = 1
            else:
                digits[leng - i] = digits[leng - i] + carry
                return digits
        
        if carry == 1:
            digits.insert(0, 1)
            return digits
        else:      
            return digits

