# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Backspace String Compare
# https://leetcode.com/problems/backspace-string-compare/
# 

class Solution(object):
    def backspaceCompare(self, S, T):
        """
        :type S: str
        :type T: str
        :rtype: bool
        """

        while S.find("#")>=0  : 
            
            if S.index("#")==0:
                S=S[1:]   
            else:
                S=S[:(S.index("#")-1)] + S[(S.index("#")+1):]                
    
        while T.find("#")>=0  :     
            if T.index("#")==0:
                T=T[1:]   
            else:
                T=T[:(T.index("#")-1)] + T[(T.index("#")+1):]                
        return S==T
        

