# 
# Generated by fetch-leetcode-submission project on GitHub.
# https://github.com/gitzhou/fetch-leetcode-submission
# Contact Me: aaron67[AT]aaron67.cc
# 
# Backspace String Compare
# https://leetcode.com/problems/backspace-string-compare/
# 

class Solution(object):
    def backspaceCompare(self, S, T):
        """
        :type S: str
        :type T: str
        :rtype: bool
        """
        len1 = len(S)
        len2 = len(T)
        while "#" in S:
            index = S.index("#")
            if index == 0:
                    S = S[1:]
            elif index == len(S) - 1:
                    S = S[:index-1]
            else:
                    S = S[:index-1]+S[index+1:]
       
        while "#" in T:
            index2 = T.index("#")
            if index2 == 0:
                    T = T[1:]
            elif index2 == len(T) - 1:
                    T = T[:index2-1]
            else:
                    T = T[:index2-1]+T[index2+1:]
        print(S)
        print(T)
        return S==T
        

